### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [shivareddyiirs/QRealTime#1]
![missing](https://user-images.githubusercontent.com/2510900/32362262-a7e2d5c6-c070-11e7-84ef-4473a91dc38a.png)

**Comment by shivareddyiirs** [comment]
Thanks for your suggestions. I have updated tags . But Can you please explain what is the owner field?.
![screen shot 2017-11-03 at 2 42 39 pm](https://user-images.githubusercontent.com/5653512/32366746-86282a6e-c0a5-11e7-901c-2e3867bb821c.png)

**Comment by shivareddyiirs** [comment]
Changed repository name to match with the plugin name. Also updated these details in metadata file.
![screen shot 2017-11-03 at 3 00 02 pm](https://user-images.githubusercontent.com/5653512/32367315-b57198c6-c0a7-11e7-933a-0c2182ff8523.png)

**Comment by shivareddyiirs** [comment]
Waiting for your comment to close this issue.

Thanks

**Comment by shivareddyiirs** [comment]
@NyakudyaA , waiting for your comment to close this issue

**Comment by NyakudyaA** [comment]
I will test the issue today and approve the plugin

**Comment by shivareddyiirs** [comment]
@NyakudyaA Thanks, You can use this ODK aggregate server link  https://odkproject-iirs.appspot.com/ to test the plugin functionality(in case you don't have any ODK aggregate server access)

**Comment by shivareddyiirs** [comment]
Thank @NyakudyaA . Closing this issue as plugin is approved
