### ISSUE TITLE
Dependencies and requirements.txt

### ISSUE THREAD

**Issue by joeflack4** [shivareddyiirs/QRealTime#14]
Hello~

Great looking project. I just noticed that pyxform is included as a static library in the root directory. Also, I don't see dependencies listed anywhere.

Is pyxform the only dependency? Has the statically included pyxform been modified? If not, I can make a PR to make this change.

**Comment by shivareddyiirs** [comment]
Hi,
Which branch you are looking at?
‘Master’ is for QGIS 2.18,
‘QGIS’ is for QGIS 3, ‘ ODK central ‘ for odk central in QGIS 3

I an installing Pyxform in runtime for QGIS 3 and have put static pyxform for QGIS 2 only.  There is no dependency in any other librarary. 

You can PR for QGIS 2.18 (master) to update pyxform.

**Comment by shivareddyiirs** [comment]
@joeflack4 Thanks for showing your interest in helping this project.
I would be glad if you can try out odk-central branch. I am actively looking for contribution in this branch

**Comment by shivareddyiirs** [comment]
@joeflack4 , I am closing this issue for now. But looking for your feedback and contribution.
You are welcome to PR with updated PyXform.

**Comment by joeflack4** [comment]
@shivareddyiirs Thanks for the explanations! I will send one soon then (to `master`).

**Comment by joeflack4** [comment]
@shivareddyiirs I've decided not to work on this. I actually thought the installation process was different. So now I'm not sure how I would bundle up dependencies in a QGIS plugin.

**Comment by shivareddyiirs** [comment]
I have repopened this issue as it seems there is problem with requests lib for QGIS in Mac.  If it is possible for you  to  work with QGIS 3 I have used pip install option for automatic dependency installation.

**Comment by shivareddyiirs** [comment]
I am closing this in favor of #18
