### ISSUE TITLE
Support for Kobotoolbox?

### ISSUE THREAD

**Issue by poVoq** [shivareddyiirs/QRealTime#15]
A lot of organisations use the free institutional accounts sponsored by UN-OCHA of the Kobotoolbox:
https://www.kobotoolbox.org/

I believe Kobotoolbox is an Ona.io fork but significantly diverged. I tried connecting to it via QRealTime, but it didn't work. Help apprechiated!

**Comment by shivareddyiirs** [comment]
I think below link is to go forwards @joeflack4 can you help in this project? Seems interesting.

https://kf.kobotoolbox.org/assets/?format=api

**Comment by shivareddyiirs** [comment]
I have created a branch 'kobo'.
Problem i am right now stuck is how to convert dict/xml  to xlsform?
Kobotoolbox api only allows uploading xlsform. (not xml)
@poVoq @joeflack4

**Comment by poVoq** [comment]
Sorry, can't really help, but maybe have a look at how this: https://github.com/enricofer/QgisODK supports ona.io

**Comment by poVoq** [comment]
Seems like you made progress on the "kobo" branch lately. Would it make sense to start alpha testing it?

Thanks a lot for working on this!

**Comment by shivareddyiirs** [comment]
Sure , it would help.
Right now  one can import the data into GIS from kobo server.
For vice-versa (making forms from GIS layer) is not happening

**Comment by poVoq** [comment]
https://github.com/XLSForm/pyxform
Probably the reverse of what you need?

Will try to test the one way sync with the test kobo branch. Thanks a lot!

**Comment by poVoq** [comment]
Would it be possible to configure the kobo instance? It is possible to selfhost kobo and I am trying to use it with the kc.humanitarianresponse.info server sponsored by UN OCHA.

But I am getting a keyError token, probably because it tries to log into the kobotoolbox domain.

Edit: tried in Qrealtime.py line 337 to kobo.humanitarianresponse.info but still same error. Any other places with the hardcoded URL?
Edit: after replacing also two other URLs it seems to connect.

**Comment by poVoq** [comment]
It seems to connect (you can select the right form) and also get the attribute table headings, but no actual submitted form data gets dowloaded on import.

The console complaints about line 411 in qrealtime.py: valueerror: invalid literal for int() with base 10:

Edit: the above is actually an older warning. If I import again all that come is the message: kobotoolbox: not able to collect data from aggregate

**Comment by shivareddyiirs** [comment]
Hi, Thanks for taking time to check this tool. 
Can you check first by creating an account in kobotoolbox domain.
Once that is tested and finalized we can then move to  support any Kobo instance. 

edit: I am trying to create an account in kc.humanitarianresponse.info. Will try tomorrow morning (IST) let you know

**Comment by poVoq** [comment]
I tried with a kobotoolbox.org account on a different computer and it seems to result in the same issue, i.e.
` CRITICAL    KoBoToolbox : Not able to collect data from Aggregate`

Edit: To reproduce: I downloaded the zip file from the kobo branch and used the install from zip in QGIS3.4 to install this version of the plugin (removed other versions of QRealtime before). Then I restarted QGIS and entered my kobotoolbox.org username and password in the settings dialog. Afterwards I created a .shp and rightclick on the entry and went to kobotoolbox->import. There I selected the form I created for testing purposes. After pressing ok to proceed it takes a while and finally results in the above error. However the headings in the attribute table get imported fine from Kobotoolbox.

**Comment by poVoq** [comment]
I tried again a version with the changes from the 24th of Feb.
Edit: sorry never mind, I accidentally tried again without the kobo.humanitarianresponse.info changes.
But also with these changes I still get an error: not able to collect data from kobotoolbox.

Edit2: Ahh, it seems the CSV(legacy) export URL is different? On my side it is a in a /csv subdirectory with a specific name and not export.csv like expected by this plugin.
Also: do I need to manually trigger the export in kobotoolbox?

Edit3: with kobotoolbox.org the export URL is actually working, but I still get the same error withing QGIS.

**Comment by shivareddyiirs** [comment]
The form data should be shared publicly in order to import data from non browser clients.

edit: This step is no more required

**Comment by poVoq** [comment]
Can confirm that it works on Kobotoolbox that way, but the export.CSV link isn't working with kobo.humanitarianresponse.info for some reason despite it being more or less the same.

By the way, is there a way to prevent it from duplicating entries when you import again? Or is there a better way to pull new entries from Kobo?

**Comment by shivareddyiirs** [comment]
I think we need to loop in somebody from kobotoolbox development team.

**Comment by shivareddyiirs** [comment]
We have done many improvement now

**Comment by shivareddyiirs** [comment]
> By the way, is there a way to prevent it from duplicating entries when you import again? Or is there a better way to pull new entries from Kobo?
Yes now it would avoid duplicate entries.

**Comment by poVoq** [comment]
Will it be integrated into the master branch or remain a seperate plugin?

**Comment by shivareddyiirs** [comment]
Frankly, I have not decided yet.
Any suggestions ?

**Comment by poVoq** [comment]
Seems to me like both would work.

Just please try to support also kc.humanitarianresponse.info in addition to Kobotoolbox.org as that is the main instance used by the UN and Red Cross etc.

Thanks

**Comment by shivareddyiirs** [comment]
Sure currently this branch is supporting
http://kc.humanitarianresponse.info/
I am trying to publish this as separate plugin.


Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SD'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 0135-2524126

**Comment by shivareddyiirs** [comment]
@poVoq Thanks for your keen interest and encouragement.
Before publishing this plugin, i would like to change the name of the plugin to something which easily target users can relate to.

Any suggestion or reference to forum or users where I can discuss this

**Comment by poVoq** [comment]
Hmm... not really. The ODK forum of course and I think there is a Red Cross IM Slack group somewhere.

Why not simply call it "Kobotoolbox sync" & "OpenDataKit sync"?

**Comment by poVoq** [comment]
Found a bug: The URL to media attachments does't use the right username.

For me it puts a user "sawan" which might be the user you tested it with?

**Comment by poVoq** [comment]
Another bug seems to be that only one media attachment is imported, even if there are multiple in the form.

Edit: might be an issue that the fields in my case are named very similar and qrealtime cuts off the names after 10 letters?

E.g. I have 3 photo attachments called "Take Photo from something1" etc. And in qgis only the first one shows up with the header "Take Photo"

**Comment by shivareddyiirs** [comment]
Thanks , I have removed the hard coded user-name.
@poVoq if you can give short names to these attributes and use alias for user friendly labels for  questions like "Take Photo from something1" etc.

**Comment by shivareddyiirs** [comment]
Integration of kobo branch with master would be first tested in QRealTime4.0 branch.

**Comment by shivareddyiirs** [comment]
experimental version of plugin 3.9 is uploaded to QGIS repository
