### ISSUE TITLE
Branch naming: master --> QGIS2

### ISSUE THREAD

**Issue by joeflack4** [shivareddyiirs/QRealTime#19]
## Description
To be consistent with the other branch naming, it might be a good idea to do this. Currently `master` is rather ambiguous.

## Additional information
I can't make a PR because this would require admin permissions, but the following would probably work:
```
git checkout master; \
git branch -m QGIS2; \
git push -u origin QGIS2
```
Then go to GitHub settings and designate a new master branch. Possibly QGIS3?
Then:
```
git push origin --delete master
```

**Comment by shivareddyiirs** [comment]
Thanks. I am on vacation will try to do the suggested changes  by 11 Dec

**Comment by shivareddyiirs** [comment]
Thank you very much.
I have made the changes. Now QGIS 2 is created and new master is at par with QGIS 3.

Thanks for your suggestion.
