### ISSUE TITLE
Translate to Spanish

### ISSUE THREAD

**Issue by shivareddyiirs** [shivareddyiirs/QRealTime#28]
**Is your feature request related to a problem? Please describe.**
There are few Spanish users who would be benefited if the plugin is translated into Spanish 
**Describe the solution you'd like**
There should be translation file created for Spanish language.
**Describe alternatives you've considered**
No Alternatives available
**Additional context**

**Comment by shivareddyiirs** [comment]
@maracarolinarojas , can you help?

**Comment by Blask0** [comment]
I can help you @shivareddyiirs

**Comment by shivareddyiirs** [comment]
>I can help you @shivareddyiirs 

@Blask0 hey  ,
Thanks , I would send you links to get started. I am also trying first time so bear with me.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maracarolinarojas** [comment]
> @maracarolinarojas , can you help?

Sure, I can help too! Let me know how. I am at your disposal.

**Comment by shivareddyiirs** [comment]
[https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#translation](https://docs.qgis.org/3.4/en/docs/pyqgis_developer_cookbook/plugins/plugins.html#translation)

@maracarolinarojas
@Blask0
<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shivareddyiirs** [comment]
Hi @maracarolinarojas  @Blask0 ,

I have  generated  ts file for Spanish.
Goto branch QRealTime4.0 and open this file
i18n/QRealTime_sp.ts

And start translating. Generally people use Qt Linguist to  edit .ts files.

Thanks for showing interest

**Comment by shivareddyiirs** [comment]
Before translation
```
<message>
        <location filename="../QRealTime_dialog.py" line="537"/>
        <source>Enter url in settings</source>
        <translation type="unfinished"></translation>
    </message>
```

after translation

```
<message>
        <location filename="../QRealTime_dialog.py" line="537"/>
        <source>Enter url in settings</source>
        <translation ">"Spanish Text Here"</translation>
    </message>

```
In this way you can change individual entries. (if not using Qt Linguist).
If you think some messages are need not to be translated just skip it.

@Blask0 @maracarolinarojas

**Comment by Blask0** [comment]
https://github.com/shivareddyiirs/QRealTime/pull/33 Have a look here.

**Comment by shivareddyiirs** [comment]
@rosaguilar, Thanks for the your input.
@Blask0 can you please check the latest version of ts and complete remaining.

Thanks

**Comment by rosaguilar** [comment]
> @rosaguilar, Thanks for the your input.
> @Blask0 can you please check the latest version of ts and complete remaining.
> 
> Thanks
I was not sure about using html codes for ñ, á and so on. Sorry about that.

**Comment by shivareddyiirs** [comment]
> 
> 
> > @rosaguilar, Thanks for the your input.
> > @Blask0 can you please check the latest version of ts and complete remaining.
> > Thanks
> > I was not sure about using html codes for ñ, á and so on. Sorry about that.

If you can use Qt linguist to check the .ts file it would be easy and fast . 
It is available QGIS 3.10\apps\Qt5\bin

As per spanish is concerned, I am blindly believing you

**Comment by rosaguilar** [comment]
> > > @rosaguilar, Thanks for the your input.
> > > @Blask0 can you please check the latest version of ts and complete remaining.
> > > Thanks
> > > I was not sure about using html codes for ñ, á and so on. Sorry about that.
> 
> If you can use Qt linguist to check the .ts file it would be easy and fast .
> It is available QGIS 3.10\apps\Qt5\bin
> 
> As per spanish is concerned, I am blindly believing you

I just noticed that those characters were not well displayed in Github, but @Blask0 fix those.

**Comment by shivareddyiirs** [comment]
Just now published the new experimental version of the plugin. (v 3.9.6)

You may have to change configuration in plugin manager to allow experimental plugins.

Try it out and raise  issue if any. This will help in porting this to a stable release.

**Comment by shivareddyiirs** [comment]
> 
> 
> > > > @rosaguilar, Thanks for the your input.
> > > > @Blask0 can you please check the latest version of ts and complete remaining.
> > > > Thanks
> > > > I was not sure about using html codes for ñ, á and so on. Sorry about that.
> > 
> > 
> > If you can use Qt linguist to check the .ts file it would be easy and fast .
> > It is available QGIS 3.10\apps\Qt5\bin
> > As per spanish is concerned, I am blindly believing you
> 
> I just noticed that those characters were not well displayed in Github, but @Blask0 fix those.

@Blask0 @rosaguilar , Do check in the latest experimental version of the plugin. 
It includes all the changes. I would be glad to have your feedback.

**Comment by shivareddyiirs** [comment]
@maracarolinarojas 
Reopening this issue

**Comment by maracarolinarojas** [comment]
Shiva, I proposed to you some changes in order to make better translations in the code. 
Anyway, I got some doubts I would like you could response to me, so I can finish the traslation in a better way in some lines. 

Line 27: <source>Not able to collect data from Aggregate</source> What doy you mean with "Aggregate"? You mean the Aggregate server?
Line 164: When you refers to "Make Online" is it when you create a form in QGIS and using this option you could export the form to the server? I'm OK? 
Line 214: When you write "Tab 1" are you meaning a form? a table? 


In addition, I translated everything that was under the following condition: <translation type="unfinished"></translation>

Best Regars, 

Mara C. Rojas

**Comment by maracarolinarojas** [comment]
Dear Shiva, when I make the Pull-request it's says "Failure: greetings". 
I attach two images for you to review about the error. I don't know if I'm doing something wrong. I apologize, I'm new in this. If it is OK, and you can see the changes let me know please. 

![Message2](https://user-images.githubusercontent.com/54945279/77833471-4a6e7f80-711c-11ea-8104-aded0d5bdb98.png)
![Message](https://user-images.githubusercontent.com/54945279/77833275-dd0e1f00-711a-11ea-8474-d0dfdce3119d.png)

**Comment by shivareddyiirs** [comment]
I can see the changes.

You are right about ‘Make online’, I meant this layer can be edited online from web or mobile app .
The greeting action of github is supposed to encourage first time pull request contributors. 

- But I think it is doing opposite :).
