### ISSUE TITLE
Support for ODK-Central

### ISSUE THREAD

**Issue by shivareddyiirs** [shivareddyiirs/QRealTime#31]
**Is your feature request related to a problem? Please describe.**
Support upcoming replacement of Aggregate from ODK

**Describe the solution you'd like**
Code migration to QRealTime4.0 branch from odk-central and

**Comment by PieterBenjamin** [comment]
@shivareddyiirs is this still an open issue? Looking on the [forum](https://forum.getodk.org/t/qrealtime-a-qgis-plug-in-for-odk/13809/11) I thought that ODK-Central had been supported for a while now.

**Comment by shivareddyiirs** [comment]
Yes it is open. I have created a branch to work with beta version.
Are you interested in adding this feature to plugin? @PieterBenjamin

**Comment by PieterBenjamin** [comment]
@shivareddyiirs I'm with [Impact++](https://sites.google.com/view/udubimpact) as are Chandni and Ratik, who should be commenting soon. We'd love to help with this feature.

**Comment by chandnirajasekaran** [comment]
Hi @shivareddyiirs, this is Chandni and I will be working with Ratik to see how Impact++ can help out in fixing this issue. We had a chance to look through the ODK Central documentation and also look through the code to see how the Aggregate server is currently being incorporated in the plugin. We would love if you could provide some more direction on where you would like us to focus our efforts in addressing this problem.

**Comment by shivareddyiirs** [comment]
Hi Chandni and Ratik,
I am glad that you are interested in contributing to this plugin.
You can create separate branch and add ODK Central support.
So we would be having 3 server support (ODK Aggregate, ODK Central and Kobo
Toolbox).

The first step would be to add ODK central in Settings menu.
Second would be to inherit the KoboToolbox Class and extend/override its
functionalities.

If required , we can do online meeting to discuss further.

Shiva

**Comment by chandnirajasekaran** [comment]
@shivareddyiirs Thank you for the clarification! We have downloaded the ODK Central branch and started taking steps towards implementing ODK central in the Settings menu, but we came up with a few follow-up questions that we wanted to discuss, so would you be available for an online meeting sometime tomorrow?

**Comment by shivareddyiirs** [comment]
Yes.
You can share the meeting link preferably anytime between 11 to 5:30 PM
(IST)

Shiva

**Comment by chandnirajasekaran** [comment]
Here is the meeting link: https://meet.google.com/uqg-xyre-erj
We will be available to meet at 11:00 am (IST).

**Comment by shivareddyiirs** [comment]
Can you please make it around 12 (IST)

Shiva Reddy Koti
Scientist/Engg.
Indian Institute of Remote Sensing
Indian Space Research Organisation
India

**Comment by ratikkoka** [comment]
Hi Shiva!

We can definitely move it to 12. We look forward to talking to you!

**Comment by shivareddyiirs** [comment]
Great, thanks!
I am ready now can join the meeting now.


Shiva

**Comment by ratikkoka** [comment]
Hi Shiva!

You can join here: https://meet.google.com/uqg-xyre-erj

**Comment by shivareddyiirs** [comment]
"ODK_Central" is the new  branch for development of this feature.

**Comment by shivareddyiirs** [comment]
@chandnirajasekaran
Hi ,
I have uploaded the experimental version of the plugin to qgis repo. This  includes changes incorporated by you for support of ODK central.
May I request you to propose changes in changelog in metadata file to include credit to your team and individuals who contributed to it.
Also feel free to suggest further changes in documentation and code.

Now onwards any changes in ODK_Central branch can be directly tested in experimental version of plugin from QGIS repo.

Thanks

regards,

**Comment by chandnirajasekaran** [comment]
Hi,

I finally had a chance to propose changes for the metadata to include credit for our team. Let us know if I should add or change anything :) 

Thank you,
Chandni R.

**Comment by samlevy3** [comment]
Hello! 

My name is Sam and I am taking over from Hugh as the project manager of Impact++. I just wanted to give an update that we are finishing the onboarding process of most of our developers are new to ODK and one of our initial tasks is to finish supporting ODK-Central by implementing the functionality of pushing the data from QGIS to the server.

**Comment by shivareddyiirs** [comment]
> Hello! 
> 
> 
> 
> My name is Sam and I am taking over from Hugh as the project manager of Impact++. I just wanted to give an update that we are finishing the onboarding process of most of our developers are new to ODK and one of our initial tasks is to finish supporting ODK-Central by implementing the functionality of pushing the data from QGIS to the server. 

Hi Sam,
Glad to know the update.
I would be glad to mentor developers

**Comment by samlevy3** [comment]
We would really appreciate the guidance! We are reading through the codebase now but I think it would be helpful to set up a meeting in a week or two after we are done to ensure we are on the right track if that is something you have the time for!

**Comment by shivareddyiirs** [comment]
In recent commits I have done major changes related to how the download is being done. Earlier it used to block the UI and Now by using QgsTask it is running in background.

Some of the todo in my mind are"
 
1. Test new commit related to QgsTaks  for ODK Central.
2.  Adding project name in kobo tab of settings similar to ODK Central. And corresponding changes in API call.
3. Currently each time QGIS is opened , the setting default to ODK Aggregate. If user is opening same project then prev. server selection should be restored.
4. After make online is successful, in the message the url of newly created form can be shown for both kobo and ODK Central.
5. Many users wants images to be downloaded and kept locally , currently we are storing links to the images. (can it be done without complicating the UI ?)
