### ISSUE TITLE
TypeError on import of data--support for koboToolbox instances other than humanitarian

### ISSUE THREAD

**Issue by Saijin-Naib** [shivareddyiirs/QRealTime#37]
**Describe the bug**
Trying to import data from an example KoBoToolbox form published online and the import fails with this error.

```
An error has occurred while executing Python code: 

TypeError: string indices must be integers 
Traceback (most recent call last):
  File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 272, in importData
    service.importData(layer,selectedForm,True)
  File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 727, in importData
    self.collectData(layer,selectedForm,importData,self.layer_name,self.version,self.geoField)
  File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 421, in collectData
    response, remoteTable = self.getTable(xFormKey,importData,topElement,version)
  File "C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 794, in getTable
    if str(form['id_string'])==XFormKey:
TypeError: string indices must be integers


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.10.1-A Coruña A Coruña, ef24c526da 

Python Path:
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\networks
C:/OSGeo4W64/apps/qgis/./python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W64/apps/qgis/./python/plugins
C:\OSGeo4W64\bin\python37.zip
C:\OSGeo4W64\apps\Python37\DLLs
C:\OSGeo4W64\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\username\AppData\Roaming\Python\Python37\site-packages
C:\OSGeo4W64\apps\Python37
C:\OSGeo4W64\apps\Python37\lib\site-packages
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32
C:\OSGeo4W64\apps\Python37\lib\site-packages\win32\lib
C:\OSGeo4W64\apps\Python37\lib\site-packages\Pythonwin
C:/Users/username/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\username\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QRealTime
Q:/User/username/Projects/QGIS
```

**To Reproduce**
Import data from KoBoToolbox to Memory Layer of type Point.

**Expected behavior**
Import will not fail on TypeError: string indices must be integers

**Screenshots**

QGIS version | 3.10.1-A Coruña | QGIS code revision | ef24c526da
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.0.2 | Running against GDAL/OGR | 3.0.2
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.2.1 | Running against PROJ | Rel. 6.2.1, November 1st, 2019
OS Version | Windows 10 (10.0)
Active python plugins | CalculateGeometry; MemoryLayerSaver; networks; openlayers_plugin; PluginLoadTimes; QRealTime; realcentroid; refFunctions; snail; SpreadsheetLayers; db_manager; processing

**Comment by shivareddyiirs** [comment]
@Saijin-Naib  Can you try with latest version of QRealTime4.0 branch, recent commit should resolve this bug.

Thanks for taking time to test the code.

**Comment by shivareddyiirs** [comment]
I have tested with humanitarian instance of koboToolBox, 
This version currently supports only humanitarian instance.

**Comment by Saijin-Naib** [comment]
@shivareddyiirs , Tried with the latest 4.0 branch, same issue.

Thanks for looking into it.

**Comment by shivareddyiirs** [comment]
Thanks for your feedback. 
I have some issues with kobotoolbox API for downloading the submissions. Therefore it  is hardcoded to work only with humanitarian instance. 

Looking forward for some help.

**Comment by shivareddyiirs** [comment]
@sawanrawat hey, may be you can help with this issue. 
Check out QReaLTime4.0 branch.

**Comment by shivareddyiirs** [comment]
In recent changes I have removed hard coded humanitarian instance url. Now it should work with other instance also.
@

**Comment by shivareddyiirs** [comment]
@prabhakaralok 
Please confirm, if we can close this issue

**Comment by shivareddyiirs** [comment]
@Saijin-Naib 
Please confirm, if this issue be closed.

**Comment by shivareddyiirs** [comment]
@Saijin-Naib 
closing it for now.
Feel free to open it in case you face similar problem.
