### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by cesarcorreo** [shivareddyiirs/QRealTime#42]
I'm trying to connect my Google drive with the plugin.  
I dont know how to fill url, user, pasword and lastID. 
I'm tried several options but no exit.
(Sorry for the basic question)
Thanks in advance

**Comment by shivareddyiirs** [comment]
Hi,
We don't support google drive.

Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SE’
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 0135-2524126
