### ISSUE TITLE
QRealTime settings window is too small (UI issue)

### ISSUE THREAD

**Issue by wenjunsun** [shivareddyiirs/QRealTime#57]
Hello! This is not a huge issue, but I am on Windows and when I open up the QRealTime settings it has a really small window, and even if I drag to enlarge it it wouldn't automatically resize the window correctly, as shown below. If there is any potential fix I would be happy to help out to iron out this issue.
![image](https://user-images.githubusercontent.com/18237212/108571055-27b10080-72c4-11eb-9a5f-66526ab8386a.png)
![image](https://user-images.githubusercontent.com/18237212/108571260-a3ab4880-72c4-11eb-877d-dee5c208801e.png)

please complete the following information):
 - OS: [Windows 10 Pro, 64 bit]
 - QGIS Version [3.16.3]
 - Plugin Version [3.8.1]

**Additional context**

**Comment by shivareddyiirs** [comment]
Hey can you please try the latest experimental version and confirm if the same problem exist.

**Comment by wenjunsun** [comment]
I figured out a way to change the size of window parameter inside of `QRealTime_dialog.py` so it is good now!
