### ISSUE TITLE
QRealTime plugin: When Form name and id is different or 'location' field is used in place of 'geometry'

### ISSUE THREAD

**Issue by ghost** [shivareddyiirs/QRealTime#6]
I exported results from ODK Aggregate VM, which is hosted locally, created a shapefile from the csv, right click and hit import, and the error QRealTime Plugin: Form is Invalid. Am I missing a step here?

**Comment by shivareddyiirs** [comment]
You just need to create a blank shapefile (no need to create shapefile from csv) and click import button. 
Before that there should be a valid aggregate server link in the plugin configuration.
Please check the aggregate url.
 if possible send me the screenshot of configuration and error

**Comment by ghost** [comment]
![screenshot 51](https://user-images.githubusercontent.com/5706644/40290846-d8105d1c-5c75-11e8-88c3-a636c8c9646a.jpg)
![screenshot 52](https://user-images.githubusercontent.com/5706644/40290885-1902503c-5c76-11e8-99bd-2dca3da42f74.png)
I followed your directions and made a blank shapefile with the same result

**Comment by shivareddyiirs** [comment]
i think url is not complete

Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SC'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 8791806093

**Comment by prabhakaralok** [comment]
Can you share xml of your form (if possible) or at least few field names (including geometry fields) e.g. fields in my form are:

GEOMETRY:Latitude
GEOMETRY:Longitude
GEOMETRY:Altitude
GEOMETRY:Accuracy
id
Type
Damage
Photo
--------
--------
Remarks
ODKUUID

Please see the video on homepage for knowing complete process of importing data

**Comment by ghost** [comment]
Here is the xml file of the form. The geometry fields are in one field called location

**Comment by ghost** [comment]
![screenshot 55](https://user-images.githubusercontent.com/5706644/40291752-aa00e418-5c7b-11e8-9d86-274a446151a4.png)
it shows up as multiple fields in aggregate though

**Comment by ghost** [comment]
I am also able to download the schema from the current configuration, but no records. So it is connecting!

**Comment by shivareddyiirs** [comment]
I am able to reproduce the error.
Thanks for your feedback. We would update you soon.

Once again thanks for bringing this up.

**Comment by ghost** [comment]
My pleasure! I am glad I can help, and that I wasn't messing something up somehow. Thank you for your time and effort with this. It will greatly improve my workflow!

**Comment by shivareddyiirs** [comment]
@amped1 
I have tested with one submission to your form.
I think now it works.

Please feel free to test and give us feedback

**Comment by amped1** [comment]
My pleasure! I am glad I can help, and that I wasn't messing something up somehow. Thank you for your time and effort with this. It will greatly improve my workflow!
