### ISSUE TITLE
QPyNullVariant object has no attribute '__getitem__' error 

### ISSUE THREAD

**Issue by Emic37** [shivareddyiirs/QRealTime#7]
Impossible to install QRealTime extension. Qgis 2.18.20 returns this error : 

> QPyNullVariant object has no attribute '__getitem__'

I work on OS X. How to correct that to use extension ? Thanks.

**Comment by shivareddyiirs** [comment]
Hi,
While I would try to reproduce the error, I suggest you to use QGIS 3 and try using our plugin. 
Let me know if same problem is faced there also.
