### ISSUE TITLE
404.1 error when Importing from ODK Central 1.5

### ISSUE THREAD

**Issue by gcniat** [shivareddyiirs/QRealTime#71]
**Describe the bug**
I get the "not able to connect to server" warning  when I connect to ODK Central 1.5.3 deployed with Central when I try to import data from a form. Even though the user and password passes the connection dialogue box and I am able to see all the forms in the project, I get the same error: "not able to connect to server".

**To Reproduce**
Usinng ODK Central version  1.5.3 deployed online
1. Go to QRealTime
2. Fille ODK Central credential and the project and validate - no error
3. Righ click a shapefile layer and chose QRealTime in the menu, then Import
4. In the dialogue, select the form you wan to import from
5. Validate

**Expected behavior**
Normally we expect the layer to start receiving points from the form's data and appearing on the map

**Screenshots**
We instead receive nothing, but a wanring message saying: "not able to connect to server". After adding a code to read the entire error, I saw it being error 404.1 that says it could not find the requested items. (paraphrased)

please complete the following information):
 - OS: Windows 10
 - QGIS Version 3.22.11
 - Plugin Version [e.g. 4.2.2 (experimental)

**Additional context**
After checking the python code, I understood that the construction of the argument for the GET command was not correct. Instead of using the name of the form I used changed it to the xmlFormId of the form. The Import works well now with me. But I am not sure to share this version to the GitHub because I can't test the Upload in production. I will be happy to help and see the whole version corrected.

**Comment by shivareddyiirs** [comment]
Thanks. Is there any change in ODK central API recently. Can you check with prev version.
Also QGIS log message view can also help in debugging.
