### ISSUE TITLE
Install error in qgis v 3.28.5

### ISSUE THREAD

**Issue by etorresmoya** [shivareddyiirs/QRealTime#73]
I can't install qrealtime version 4.4.4 in QGIS 3.28.5. I receive this error.

No se pudo cargar el complemento 'QRealTime' debido a un error al llamar a su método initGui() 

TypeError: setText(self, str): argument 1 has unexpected type 'int' 
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 216, in initGui
    self.add_action(icon_path,text=self.tr(u'QRealTime Setting'),callback=self.run,parent=self.iface.mainWindow())
  File "C:\Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime.py", line 174, in add_action
    self.dlg = QRealTimeDialog(self)
  File "C:\Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 114, in __init__
    serviceClass(container,caller)
  File "C:\Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QRealTime\QRealTime_dialog.py", line 159, in __init__
    self.cellWidget(row,1).setText(parameter[1])
TypeError: setText(self, str): argument 1 has unexpected type 'int'

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.28.5-Firenze Firenze, 50adba36f2 

Ruta de Python:
C:/OSGeo4W/apps/qgis-ltr/./python
C:/Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGeo4W/apps/qgis-ltr/./python/plugins
C:\OSGeo4W\bin\python39.zip
C:\OSGeo4W\apps\Python39\DLLs
C:\OSGeo4W\apps\Python39\lib
C:\OSGeo4W\bin
C:\OSGeo4W\apps\Python39
C:\OSGeo4W\apps\Python39\lib\site-packages
C:\OSGeo4W\apps\Python39\lib\site-packages\win32
C:\OSGeo4W\apps\Python39\lib\site-packages\win32\lib
C:\OSGeo4W\apps\Python39\lib\site-packages\Pythonwin
C:/Users/etorr/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\etorr\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QRealTime
please complete the following information):
 - OS: windows
 - QGIS Version 3.28.5
 - Plugin Version 4.4.4

![image](https://github.com/shivareddyiirs/QRealTime/assets/36379571/3327cd39-59e1-4200-af8a-14c2ce484d5c)

**Comment by shivareddyiirs** [comment]
Thank you very much for raising this bug.This is happening to those who are installing plug-in for first time in their system.That the reason we could not detected earlier.Wishing 24 hours ,I would be releasing the updated version. Then you should be able to install.Feel free to comment on documentation too.
