### ISSUE TITLE
Connection to other servers

### ISSUE THREAD

**Issue by shapley** [shivareddyiirs/QRealTime#74]
Would it be possible in a future version for another Kobo server to be specified where an individual installation has been undertaken?

**Comment by shivareddyiirs** [comment]
> Would it be possible in a future version for another Kobo server to be specified where an individual installation has been undertaken?

Sure, I think just changing the URL should work like currently both humanitarian and normal server are supported under same kobo category. Any installation of kobo should work.

If you have any such server do try and let me know if it don't work. I would be more than happy to improve over it

**Comment by shapley** [comment]
The QGIS log shows:

2023-06-11T09:17:09     CRITICAL    Kobo : Invalid url username or password
2023-06-11T09:17:09     CRITICAL    Kobo : can not connect to server

The url is:

https://kobo.beacons-npa.gov.uk/accounts/login/

I tried shortening to 

https://kobo.beacons-npa.gov.uk/

But the same error. I can login normally with Firefox or any other browser.

**Comment by shivareddyiirs** [comment]
I think trick is to identify the url prefix for API call. Also some details of the kobo installation version etc. may help.


If you have possibility of creating any temporary user and provide me the credentials, then I think I would be able to crack the issue.

Once again thanks for testing our plugin with your installation

**Comment by shivareddyiirs** [comment]
Hey , I could create account myself to this server. Would soon test and post it here

**Comment by shivareddyiirs** [comment]
I have tried with below url:
https://kobo.beacons-npa.gov.uk/

I have tested creating form (make online), and sync after data collection.
All working fine.
