### ISSUE TITLE
pyxform not installed in xubuntu

### ISSUE THREAD

**Issue by mathieubossaert** [shivareddyiirs/QRealTime#9]
Good morning,
I try to get QrealTime running on QGIS 3.2 over xubuntu 18.04 and i get this error message.

> Impossible de charger l'extension 'QRealTime' provoque une erreur lors de l'appel à sa méthode classFactory() 
> 
> NameError: name 'self' is not defined 
> Traceback (most recent call last):
>   File "/home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 50, in 
>     from pyxform.builder import create_survey_element_from_dict
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'pyxform'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 55, in 
>     from pyxform.builder import create_survey_element_from_dict
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
> ModuleNotFoundError: No module named 'pyxform'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 337, in startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/__init__.py", line 34, in classFactory
>     from .QRealTime import QRealTime
>   File "/usr/lib/python3/dist-packages/qgis/utils.py", line 665, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins/QRealTime/QRealTime.py", line 59, in 
>     self.iface.messageBar().pushWarning(self.tr("QRealTime plugin"), self.tr('install pyxform package in python3 manually'))
> NameError: name 'self' is not defined
> 
> 
> Version de Python : 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0] 
> Version de QGIS : 3.2.0-Bonn Bonn, bc43194 
> 
> Chemin Python :
> /usr/share/python-wheels/lockfile-0.12.2-py2.py3-none-any.whl
> /usr/share/python-wheels/pip-9.0.1-py2.py3-none-any.whl
> /usr/share/python-wheels/idna-2.6-py2.py3-none-any.whl
> /usr/share/python-wheels/packaging-17.1-py2.py3-none-any.whl
> /usr/share/python-wheels/pyparsing-2.2.0-py2.py3-none-any.whl
> /usr/share/python-wheels/webencodings-0.5-py2.py3-none-any.whl
> /usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl
> /usr/share/python-wheels/pkg_resources-0.0.0-py2.py3-none-any.whl
> /usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl
> /usr/share/python-wheels/appdirs-1.4.3-py2.py3-none-any.whl
> /usr/share/python-wheels/wheel-0.30.0-py2.py3-none-any.whl
> /usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl
> /usr/share/python-wheels/certifi-2018.1.18-py2.py3-none-any.whl
> /usr/share/python-wheels/chardet-3.0.4-py2.py3-none-any.whl
> /usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl
> /usr/share/python-wheels/distlib-0.2.6-py2.py3-none-any.whl
> /usr/share/python-wheels/setuptools-39.0.1-py2.py3-none-any.whl
> /usr/share/python-wheels/colorama-0.3.7-py2.py3-none-any.whl
> /usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl
> /usr/share/python-wheels/ipaddress-0.0.0-py2.py3-none-any.whl
> /usr/share/python-wheels/html5lib-0.999999999-py2.py3-none-any.whl
> /usr/share/python-wheels/progress-1.2-py2.py3-none-any.whl
> /usr/share/python-wheels/retrying-1.3.3-py2.py3-none-any.whl
> /usr/share/qgis/python
> /home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python
> /home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python/plugins
> /usr/share/qgis/python/plugins
> /usr/lib/python36.zip
> /usr/lib/python3.6
> /usr/lib/python3.6/lib-dynload
> /usr/local/lib/python3.6/dist-packages
> /usr/lib/python3/dist-packages
> /home/mathieu/.local/share/QGIS/QGIS3/profiles/default/python

**Comment by shivareddyiirs** [comment]
Can you install pyxform library into python used by QGIS mannually.
I think plugin is not able to install it automatically.

Thanks & Regards
Shiva Reddy K.
Scientist/Engineer 'SC'
Indian Institute of Remote Sensing,
Indian Space Research Organisation
Department of Space
4-Kalidas Road
Dehradun
mobile: 8791806093

**Comment by mathieubossaert** [comment]
I did `pip install pyxform` but I get the same error

**Comment by shivareddyiirs** [comment]
Hi,
Please verify if you have installed [qgis-python](https://gis.stackexchange.com/questions/285289/enabling-python-plugins-on-qgis3-linux)

**Comment by shivareddyiirs** [comment]
you need to install pyxform into python 3.
It can be either done by pip3 install pyxform or python3 -m pip install pyxform 
Check that you have updated plugin to latest version.

I am closing this issue
