### ISSUE TITLE
All Photo Attributs of one Point have the same URL

### ISSUE THREAD

**Issue by misterbuchi** [shivareddyiirs/QRealTime#91]
We have a survey, where we add to one point 2-3 Photos. When we import the collected data the data imports fine except the attributs with contains links to the photos. We usually get the URL of the last photo in every field. 

![Bildschirmfoto 2023-10-11 um 18 07 51](https://github.com/shivareddyiirs/QRealTime/assets/49162038/34a35c1e-1861-43c3-9732-9ea75234e5d8)

please complete the following information):
- selfhosted Kobocollect server
 - OS: MacOS
 - QGIS Version 3.2
 - Plugin Version 4.1

**Additional context**

**Comment by shivareddyiirs** [comment]
Dear Dominik Bucheli (@misterbuchi )
please update to latest 4.4.2 version. 
Thank you very much for the bug reporting.

**Comment by misterbuchi** [comment]
@shivareddyiirs Thank you very much for fixing that one so fast.
